export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 100;

export const INVALID_CURRENT_PASSWORD_ERROR_CODE = 'INVALID_CURRENT_PASSWORD';
export const PASSWORD_RESET_TTL_MINUTES = 60;
