export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 100;

export const INVALID_CURRENT_PASSWORD_ERROR_CODE = 'INVALID_CURRENT_PASSWORD';

export const EMAIL_NOT_VERIFIED_ERROR_CODE = 'EMAIL_NOT_VERIFIED';
