ALTER TYPE "EnergyLedgerReason" ADD VALUE 'BADGE_REWARD';

CREATE TYPE "BadgeId" AS ENUM ('LOGIC_PROGRESSION', 'LOGIC_EXCELLENCE', 'LOGIC_PERFECTION', 'MEMORY_PROGRESSION', 'MEMORY_EXCELLENCE', 'MEMORY_PERFECTION', 'DISCRIMINATION_PROGRESSION', 'DISCRIMINATION_EXCELLENCE', 'DISCRIMINATION_PERFECTION', 'REACTIVITY_PROGRESSION', 'REACTIVITY_EXCELLENCE', 'REACTIVITY_PERFECTION', 'MOTOR_PROGRESSION', 'MOTOR_EXCELLENCE', 'MOTOR_PERFECTION', 'EXAM_FIRST', 'EXAM_FAVORABLE', 'EXAM_SOLID', 'FIRST_STEPS', 'SECTOR_MASTERY');

ALTER TABLE "User" ADD COLUMN "tutorialDiscoveredAt" TIMESTAMP(3);

DROP TABLE "UserBadge";

DROP TABLE "Badge";

DROP TYPE "BadgeCategory";

CREATE TABLE "UserBadge" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "badgeId" "BadgeId" NOT NULL,
    "earnedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "acknowledgedAt" TIMESTAMP(3),

    CONSTRAINT "UserBadge_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "UserBadge_userId_badgeId_key" ON "UserBadge"("userId", "badgeId");

ALTER TABLE "UserBadge" ADD CONSTRAINT "UserBadge_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "BadgeRarity" (
    "badgeId" "BadgeId" NOT NULL,
    "eligibleCount" INTEGER NOT NULL,
    "earnedCount" INTEGER NOT NULL,
    "computedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BadgeRarity_pkey" PRIMARY KEY ("badgeId")
);
