export enum AxisType {
  LOGIC = 'LOGIC',
  MEMORY = 'MEMORY',
  VISUAL_DISCRIMINATION = 'VISUAL_DISCRIMINATION',
  REACTIVITY = 'REACTIVITY',
  MOTOR_SKILLS = 'MOTOR_SKILLS',
  ATTENTION = 'ATTENTION',
  NUMERICAL = 'NUMERICAL',
  VERBAL = 'VERBAL',
  SPATIAL = 'SPATIAL',
  // MULTITASKING = 'MULTITASKING' - reserved (aviation), not implemented
}
