export enum ShapeId {
  TRIANGLE = 'TRIANGLE',
  SQUARE = 'SQUARE',
  CIRCLE = 'CIRCLE',
  RECTANGLE = 'RECTANGLE',
  TRAPEZOID = 'TRAPEZOID',
  TRAPEZOID_RIGHT = 'TRAPEZOID_RIGHT',
  TRAPEZOID_LEFT = 'TRAPEZOID_LEFT',
}
